### ISSUE TITLE
Doublebuffering performance

### ISSUE THREAD

**Issue by qrmcat** [qrmcat/PlotOS#5]
Currently, the DoubleBuffering library only gpu.sets the pixels, which makes performance not great when having lots of pixels of the same color, character, and background color next to eachother. This can be fixed by making a fast algorithm to group pixels together into bigger rectangles, then using gpu.fill().

**Comment by Ocawesome101** [comment]
it may be worth using the VRAM capabilities of modern OpenComputers if they're available;  that will significantly speed up double-buffering if done right.  ideally don't depend on it, though, since the last CurseForge build of OC doesn't have them.

**Comment by qrmcat** [comment]
Probably yes. Though, about 80% of the current slowness comes from using gpu.set even when with a really optimized algorithm, drawing a screen with a window open would take like 6-7 fill calls and like 20 gpu.set if drawing from zero, and like one fill call and 3-6 set calls if the window is moved by only a pixel or so, but that is just an assumption.

**Comment by Ocawesome101** [comment]
Dirty tracking would also be good. That and a way to group pixels and I think you'd see much better performance.

**Comment by qrmcat** [comment]
I'm going to be closing this issue for now as I am replacing the usage of the double buffering library with the GPU VRAM.
